const mongoose=require('mongoose');
const ProblemSchema=new mongoose.Schema({
     contestName:{
         type:String,
         require:true
     },
     problemName:{
        type:String,
        require:true,
        unique:true
    },
    score:{
        type:String,
        require:true
    },
    problem_statement:{
        type:String,
        require:true
    },
    input_format:{
        type:String,
        require:true
    },
    output_format:{
       type:String,
       require:true
   },
   constraints:{
       type:String,
       require:true
   },
   
   sample_input:{
       type:String,
       require:true
   },
   sample_output:{
       type:String,
       require:true
   },
   explanation:{
       type:String,
       require:true
   },
   testcase1:{
       type:String,
       require:true
   },
   testcase2:{
       type:String,
       require:true
   },
   testcase3:{
       type:String,
       require:true
   },
   testcase4:{
       type:String,
       require:true
   },
   testcaseo1:{
       type:String,
       require:true
   },
   testcaseo2:{
       type:String,
       require:true
   },
   testcaseo3:{
       type:String,
       require:true
   },
   testcaseo4:{
       type:String,
       require:true
   }
});
const addProb=new mongoose.model('Problem',ProblemSchema);
module.exports=addProb;